services:
    mysql:
        image: mysql:5.7
        container_name: auth-database
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DATABASE_PASS}"
            MYSQL_DATABASE: "${DATABASE_NAME}"
            MYSQL_USER: "${DATABASE_USER}"
            MYSQL_PASSWORD: "${DATABASE_PASS}"
            MYSQL_INITDB_SKIP_TZINFO: "true"
        volumes:
            - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql:ro
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "--password=${DATABASE_PASS}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    mysql_data: